services:
  gee-service:
    build:
      context: ./gee_app_with_cache_logic
      dockerfile: Dockerfile
    container_name: gee_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      FLASK_ENV: development
      FLASK_DEBUG: "True"
      REDIS_URL: ${REDIS_URL}
      GEE_SERVICE_ACCOUNT: ${GEE_SERVICE_ACCOUNT:-satellite-platform-application@adept-lodge-478616-i2.iam.gserviceaccount.com}
      GEE_KEY_PATH: /app/satellite-platform-application-f7154aa5ce46.json
      GEE_PROJECT_ID: ${GEE_PROJECT_ID:-adept-lodge-478616-i2}
    volumes:
      - ./gee_app_with_cache_logic:/app
      - ./gee_app_with_cache_logic/output:/app/output
      - ./gee_app_with_cache_logic/satellite-platform-application-f7154aa5ce46.json:/app/satellite-platform-application-f7154aa5ce46.json:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - satellite-network

  image-processing-app:
    build:
      context: ./image_porcessing
      dockerfile: Dockerfile
    container_name: image-processing-app-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
      - ./image_porcessing/app:/app
      - ./image_porcessing/output:/app/output
    networks:
      - satellite-network

networks:
  satellite-network:
    driver: bridge
    name: satellite-network
