// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geospatial.proto

package com.enit.satellite_platform.modules.resource_management.utils.communication_management.impl.grpc;

public final class GeoSpatialProto {
  private GeoSpatialProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_enit_satellite_platform_grpc_PayloadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_enit_satellite_platform_grpc_PayloadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_enit_satellite_platform_grpc_PayloadRequest_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_enit_satellite_platform_grpc_PayloadRequest_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_enit_satellite_platform_grpc_PayloadRequest_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_enit_satellite_platform_grpc_PayloadRequest_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_enit_satellite_platform_grpc_PayloadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_enit_satellite_platform_grpc_PayloadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_enit_satellite_platform_grpc_PayloadResponse_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_enit_satellite_platform_grpc_PayloadResponse_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_enit_satellite_platform_grpc_PayloadResponse_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_enit_satellite_platform_grpc_PayloadResponse_MetadataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020geospatial.proto\022 com.enit.satellite_p" +
      "latform.grpc\"\212\002\n\016PayloadRequest\022H\n\004data\030" +
      "\001 \003(\0132:.com.enit.satellite_platform.grpc" +
      ".PayloadRequest.DataEntry\022P\n\010metadata\030\002 " +
      "\003(\0132>.com.enit.satellite_platform.grpc.P" +
      "ayloadRequest.MetadataEntry\032+\n\tDataEntry" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\032/\n\rMeta" +
      "dataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001\"\215\002\n\017PayloadResponse\022I\n\004data\030\001 \003(\0132;.co" +
      "m.enit.satellite_platform.grpc.PayloadRe" +
      "sponse.DataEntry\022Q\n\010metadata\030\002 \003(\0132?.com" +
      ".enit.satellite_platform.grpc.PayloadRes" +
      "ponse.MetadataEntry\032+\n\tDataEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\032/\n\rMetadataEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012\211\001\n\021Ge" +
      "oSpatialService\022t\n\013ProcessData\0220.com.eni" +
      "t.satellite_platform.grpc.PayloadRequest" +
      "\0321.com.enit.satellite_platform.grpc.Payl" +
      "oadResponse\"\000B5\n com.enit.satellite_plat" +
      "form.grpcB\017GeoSpatialProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_enit_satellite_platform_grpc_PayloadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_enit_satellite_platform_grpc_PayloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_enit_satellite_platform_grpc_PayloadRequest_descriptor,
        new java.lang.String[] { "Data", "Metadata", });
    internal_static_com_enit_satellite_platform_grpc_PayloadRequest_DataEntry_descriptor =
      internal_static_com_enit_satellite_platform_grpc_PayloadRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_enit_satellite_platform_grpc_PayloadRequest_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_enit_satellite_platform_grpc_PayloadRequest_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_enit_satellite_platform_grpc_PayloadRequest_MetadataEntry_descriptor =
      internal_static_com_enit_satellite_platform_grpc_PayloadRequest_descriptor.getNestedTypes().get(1);
    internal_static_com_enit_satellite_platform_grpc_PayloadRequest_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_enit_satellite_platform_grpc_PayloadRequest_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_enit_satellite_platform_grpc_PayloadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_enit_satellite_platform_grpc_PayloadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_enit_satellite_platform_grpc_PayloadResponse_descriptor,
        new java.lang.String[] { "Data", "Metadata", });
    internal_static_com_enit_satellite_platform_grpc_PayloadResponse_DataEntry_descriptor =
      internal_static_com_enit_satellite_platform_grpc_PayloadResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_enit_satellite_platform_grpc_PayloadResponse_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_enit_satellite_platform_grpc_PayloadResponse_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_enit_satellite_platform_grpc_PayloadResponse_MetadataEntry_descriptor =
      internal_static_com_enit_satellite_platform_grpc_PayloadResponse_descriptor.getNestedTypes().get(1);
    internal_static_com_enit_satellite_platform_grpc_PayloadResponse_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_enit_satellite_platform_grpc_PayloadResponse_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
