// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geospatial.proto

package com.enit.satellite_platform.modules.resource_management.utils.communication_management.impl.grpc;

public interface PayloadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.enit.satellite_platform.grpc.PayloadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, bytes&gt; data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, bytes&gt; data = 1;</code>
   */
  boolean containsData(
      java.lang.String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getData();
  /**
   * <code>map&lt;string, bytes&gt; data = 1;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getDataMap();
  /**
   * <code>map&lt;string, bytes&gt; data = 1;</code>
   */
  /* nullable */
com.google.protobuf.ByteString getDataOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; data = 1;</code>
   */
  com.google.protobuf.ByteString getDataOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, string&gt; metadata = 2;</code>
   */
  int getMetadataCount();
  /**
   * <code>map&lt;string, string&gt; metadata = 2;</code>
   */
  boolean containsMetadata(
      java.lang.String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetadata();
  /**
   * <code>map&lt;string, string&gt; metadata = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetadataMap();
  /**
   * <code>map&lt;string, string&gt; metadata = 2;</code>
   */
  /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; metadata = 2;</code>
   */
  java.lang.String getMetadataOrThrow(
      java.lang.String key);
}
