### Check Conductor server connectivity
GET http://localhost:9090/api/conductor/health
Content-Type: application/json

###

### Get Conductor server info
GET http://localhost:9090/api/conductor/info
Content-Type: application/json
