package com.enit.satellite_platform.config.cache_handler.general_cache_handler;

import lombok.Data;

/**
 * Base class for holding common cache configuration properties used by {@link CacheHandler}.
 * Specific cache implementations (like those using {@code @ConfigurationProperties})
 * can extend this class or instantiate it directly to provide configuration values.
 *
 * The {@code @Data} annotation from Lombok automatically generates getters, setters,
 * {@code toString()}, {@code equals()}, and {@code hashCode()} methods.
 */
@Data
public class CachePropertiesBase {

    /**
     * Time-to-live (TTL) for entries stored in the Redis cache, specified in seconds.
     * After this duration, the entry may be automatically evicted by Redis.
     */
    private long redisTtlSeconds;

    /**
     * A prefix string added to all cache keys generated by the associated {@link ICacheKeyGenerator}.
     * This helps in organizing keys in Redis and preventing collisions between different caches.
     * Example: "satellite_processing:".
     */
    private String cachePrefix;

    /**
     * The maximum access count for an entry to be considered "infrequently used" during cache cleanup.
     * Entries with an access count less than or equal to this value AND older than the inactivity threshold
     * are candidates for removal by {@link CacheHandler#cleanInfrequentlyUsedCache()}.
     */
    private int maxInfrequentAccessCount;

    /**
     * The duration in days after which an infrequently accessed cache entry becomes eligible for cleanup.
     * An entry is considered old if its last accessed time is before (now - inactivityThresholdDays).
     * Used in conjunction with {@link #maxInfrequentAccessCount}.
     */
    private long inactivityThresholdDays;

    /**
     * Constructs a new instance of CachePropertiesBase.
     *
     * @param redisTtlSeconds          The cache entry TTL in seconds.
     * @param cachePrefix              The prefix for cache keys.
     * @param maxInfrequentAccessCount The threshold for infrequent access count during cleanup.
     * @param inactivityThresholdDays  The inactivity threshold in days for cleanup.
     */
    public CachePropertiesBase(long redisTtlSeconds, String cachePrefix, int maxInfrequentAccessCount, long inactivityThresholdDays) {
        this.redisTtlSeconds = redisTtlSeconds;
        this.cachePrefix = cachePrefix;
        this.maxInfrequentAccessCount = maxInfrequentAccessCount;
        this.inactivityThresholdDays = inactivityThresholdDays;
    }

}
